### ISSUE TITLE
Cannot build

### ISSUE THREAD

**Issue by maurelian** [ConsenSys/bytecode-verifier#13]
```
$ node -v
v10.16.0
$ npm -v
6.9.0
$ npm i

> scrypt@6.0.3 preinstall /Users/primary/Projects/Tools/bytecode-verifier/node_modules/scrypt
> node node-scrypt-preinstall.js


> scrypt@6.0.3 install /Users/primary/Projects/Tools/bytecode-verifier/node_modules/scrypt
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
  SOLINK_MODULE(target) Release/copied_files.node
  CC(target) Release/obj.target/scrypt_wrapper/src/util/memlimit.o
  CC(target) Release/obj.target/scrypt_wrapper/src/scryptwrapper/keyderivation.o
  CC(target) Release/obj.target/scrypt_wrapper/src/scryptwrapper/pickparams.o
  CC(target) Release/obj.target/scrypt_wrapper/src/scryptwrapper/hash.o
  LIBTOOL-STATIC Release/scrypt_wrapper.a
  CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.2.0/lib/crypto/crypto_scrypt.o
  CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.2.0/lib/crypto/crypto_scrypt_smix.o
  CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.2.0/libcperciva/util/warnp.o
  CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.2.0/libcperciva/alg/sha256.o
  CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.2.0/libcperciva/util/insecure_memzero.o
  CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.2.0/lib/scryptenc/scryptenc_cpuperf.o
  LIBTOOL-STATIC Release/scrypt_lib.a
  CXX(target) Release/obj.target/scrypt/src/node-boilerplate/scrypt_common.o
In file included from ../src/node-boilerplate/scrypt_common.cc:28:
In file included from ../../nan/nan.h:192:
../../nan/nan_maybe_43_inl.h:112:15: error: no member named 'ForceSet' in 'v8::Object'
  return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);
         ~~~  ^
In file included from ../src/node-boilerplate/scrypt_common.cc:28:
../../nan/nan.h:834:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(...,
      async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/primary/.node-gyp/10.16.0/include/node/node.h:176:1: note: 'MakeCallback' has been
      explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/primary/.node-gyp/10.16.0/include/node/node.h:91:20: note: expanded from macro
      'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../src/node-boilerplate/scrypt_common.cc:28:
../../nan/nan.h:849:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(...,
      async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/primary/.node-gyp/10.16.0/include/node/node.h:169:1: note: 'MakeCallback' has been
      explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/primary/.node-gyp/10.16.0/include/node/node.h:91:20: note: expanded from macro
      'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../src/node-boilerplate/scrypt_common.cc:28:
../../nan/nan.h:864:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(...,
      async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/primary/.node-gyp/10.16.0/include/node/node.h:162:1: note: 'MakeCallback' has been
      explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/primary/.node-gyp/10.16.0/include/node/node.h:91:20: note: expanded from macro
      'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../src/node-boilerplate/scrypt_common.cc:28:
../../nan/nan.h:1473:31: warning: 'MakeCallback' is deprecated: Use MakeCallback(...,
      async_context) [-Wdeprecated-declarations]
    return scope.Escape(node::MakeCallback(
                              ^
/Users/primary/.node-gyp/10.16.0/include/node/node.h:176:1: note: 'MakeCallback' has been
      explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/primary/.node-gyp/10.16.0/include/node/node.h:91:20: note: expanded from macro
      'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
4 warnings and 1 error generated.
make: *** [Release/obj.target/scrypt/src/node-boilerplate/scrypt_common.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/primary/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Darwin 19.0.0
gyp ERR! command "/Users/primary/.nvm/versions/node/v10.16.0/bin/node" "/Users/primary/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/primary/Projects/Tools/bytecode-verifier/node_modules/scrypt
gyp ERR! node -v v10.16.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scrypt@6.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the scrypt@6.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/primary/.npm/_logs/2019-12-26T16_01_12_629Z-debug.log

primary at primarys-MacBook-Pro in ~/Projects/Tools/bytecode-verifier (master●)
$ gco .
Updated 2 paths from the index

primary at primarys-MacBook-Pro in ~/Projects/Tools/bytecode-verifier (master)
$ npm i
npm ERR! path /Users/primary/Projects/Tools/bytecode-verifier/node_modules/websocket
npm ERR! code EISGIT
npm ERR! git /Users/primary/Projects/Tools/bytecode-verifier/node_modules/websocket: Appears to be a git repo or submodule.
npm ERR! git     /Users/primary/Projects/Tools/bytecode-verifier/node_modules/websocket
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/primary/.npm/_log
```

**Comment by shayanb** [comment]
builds fine with node `v12.4.0`. and `v10.16.0` for me. Not sure what the issue is there, can you try with 12.4.0?

**Comment by maurelian** [comment]
I was on master. I merged 0.3.1 into master. 
Builds fine now.

**Comment by maurelian** [comment]
I also changed the default branch back to master just to avoid future confusion.

**Comment by shayanb** [comment]
@maurelian thanks, we should merge everything into master soon.
