### ISSUE TITLE
TypeError: Cannot read property 'compile' of undefined

### ISSUE THREAD

**Issue by enderphan94** [ConsenSys/bytecode-verifier#19]
Command:
```
ethv verify ropsten erc20.sol
You've chosen: ropsten
? Enter compiler version. (e.g. v0.4.10+commit.f0d539ae). v0.5.9
? Enter the contract file name. (e.g. MultiSigWalletWithDailyLimit.sol) erc20.sol
? Enter the contract address on blockchain. (e.g. 0x851b7f3ab81bd8df354f0d7640efcd7288553419) 0xC921254a908e25d1695D677037d8901885ad6228
```
Output error:
```
Compiling in progress, dude, please be patient and give me 15~30 sec ...
Solc failed to loadedError: Error retrieving binary: Not Found
/Users/macbookpro/.nvm/versions/node/v13.6.0/lib/node_modules/eth-bytecode-verifier/src/verifier.js:34
  	var output = solc_specific.compile(input, is_optimized);
  	                           ^

TypeError: Cannot read property 'compile' of undefined
    at /Users/macbookpro/.nvm/versions/node/v13.6.0/lib/node_modules/eth-bytecode-verifier/src/verifier.js:34:31
    at ClientRequest.<anonymous> (/Users/macbookpro/.nvm/versions/node/v13.6.0/lib/node_modules/eth-bytecode-verifier/node_modules/solc/wrapper.js:205:11)
    at Object.onceWrapper (events.js:428:26)
    at ClientRequest.emit (events.js:321:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:602:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:116:17)
    at TLSSocket.socketOnData (_http_client.js:471:22)
    at TLSSocket.emit (events.js:321:20)
    at addChunk (_stream_readable.js:305:12)
    at readableAddChunk (_stream_readable.js:280:11)
    at TLSSocket.Readable.push (_stream_readable.js:214:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:186:23)
```

**Comment by enderphan94** [comment]
nvm, solc version is higher than 0.4.9
